### ISSUE TITLE
Thread safety of the maven plugin

### ISSUE THREAD

**Issue by Allsimon** [v12technology/fluxtion#24]
Building this project via `mvn clean install -T 1C` throws this warning:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in fluxtion :: examples :: docs.core:
[WARNING] com.fluxtion:fluxtion-maven-plugin:1.7.25-SNAPSHOT
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

If the plugin is indeed thread-safe, can you mark it as such please ?

**Comment by gregv12** [comment]
I think Fluxtion generator plugin will not be threadsafe with maven. There is a static generation context being passed around which has references to custom classloaders and global state. I originally designed the generator to be single threaded, with the state cleared between runs. Sequential operation on the same thread is fine. 

From a quick look how maven parallel builds work, sharing state in a static variable will be an issue. Unless Maven plugins all run in their own classloader and mutliple class definitions of the same plugin are loaded in the same JVM. I do not know enough about maven, particularly parallel builds, to give a definitive answer. 

Do you know how class loading for plugins works? 

I could fix the issue, using something like google dagger or juice to replace the static context, but it is high cost for low return at the moment I think.

**Comment by Allsimon** [comment]
I can fix this if you want

Unrelated to this issue but Dagger made me think about it: Do you mind if I use lombok ? I see multiple classes that could be cleaned.

For example:
```java
public class EventMethod {

    private String eventId;
    private boolean propagate = true;
    private String filter;

    public boolean isPropagate() {
        return propagate;
    }

    public void setPropagate(boolean propagate) {
        this.propagate = propagate;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    @Override
    public String toString() {
        return "EventMethod{" + "eventId=" + eventId + ", propagate=" + propagate + ", filter=" + filter + '}';
    }
    
}
```

to
```java
@Data
public class EventMethod {
    private String eventId;
    private boolean propagate = true;
    private String filter;
}
```

**Comment by gregv12** [comment]
Two discussions here:
1. Fixing the static context - that's quite a big task. The entry point to the generator evolved over time and using a static context allowed me to put off solving the intitialisation in a structured form. It works at the moment and there are lots of tests, but it is a re-engineering task to move to a DI style. I think it is the right thing to do and I would feel better about the whole project if the static context was removed. But it will require thought. In some places I access the context using the service loader, so that is easy to replace. But in other places I use the raw static methods on GenerationContext. Could be a tough cookie to solve.

2. Lombok - cool idea. I tried to get Lombok working with the Fluxtion maven plugin but it caused problems especially with an IDE. 
But your idea, if I understand you correctly, of using Lombok for internal classes is a good way to reduce noise. I have not used Lombok in a project only read about it so my knowledge is limited. I guess it requires special setup in the ide to enable autocomplete etc. for the Lombok generated classes.
